name: reusable - deploy stack
on:
  workflow_call:
    inputs:
      image_app_ai: { required: true, type: string }
      image_app_be: { required: true, type: string }
      stack_dir:    { required: false, type: string, default: $HOME/stack }

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-g-learn-e
      cancel-in-progress: false
    steps:
      - name: SSH & deploy both apps
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -euo pipefail
            STACK_DIR="${{ inputs.stack_dir }}"
            SEC_DIR="$STACK_DIR/secrets"
            LOG_FASTAPI_DIR="$STACK_DIR/logs/fastapi"
            LOG_SPRING_DIR="$STACK_DIR/logs/spring"
            
            sudo install -d -m 744 "$STACK_DIR" "$SEC_DIR" "$LOG_FASTAPI_DIR" "$LOG_SPRING_DIR"

            # 1) Docker Hub 로그인
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # 2) 멀티라인 시크릿 → 서버 env 파일로 생성
            sudo tee "$SEC_DIR/fastapi.env" >/dev/null <<'EOF'
            ${{ secrets.FASTAPI_ENV_FILE }}
            EOF
            sudo chmod 600 "$SEC_DIR/fastapi.env"

            # 3B) application-prod.yml (멀티라인 시크릿 → 파일)
            sudo tee "$SEC_DIR/application-prod.yml" >/dev/null <<'EOF'
            ${{ secrets.SPRING_APP_PROD_YML }}
            EOF
            sudo chmod 600 "$SEC_DIR/application-prod.yml"
            
            # 3) AUTO-GENERATE compose.yml (no version key; Compose V2)
            sudo tee "$STACK_DIR/compose.yml" >/dev/null <<YAML
            services:
              fastapi_backend:
                image: ${{ inputs.image_app_ai }}:latest
                container_name: fastapi_backend
                ports: [ "8000:8000" ]
                env_file: [ "./secrets/fastapi.env" ]
                volumes:
                  - "$LOG_FASTAPI_DIR:/app/logs"
                restart: unless-stopped
                logging: { driver: json-file, options: { max-size: "10m", max-file: "5" } }
                extra_hosts: [ "host.docker.internal:host-gateway" ]
                command: >
                  sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
                # 2) healthcheck는 nc 대신 파이썬 소켓(의존성 無)
                healthcheck:
                  test: ["CMD-SHELL","python -c \"import socket,sys; s=socket.socket(); s.settimeout(1); sys.exit(0 if s.connect_ex(('localhost',8000))==0 else 1)\""]
                  interval: 5s
                  timeout: 3s
                  retries: 30
                  start_period: 5s
                  
              spring_backend:
                image: ${{ inputs.image_app_be }}:latest
                container_name: spring_backend
                ports: [ "8080:8080" ]
                environment:
                  - SPRING_PROFILES_ACTIVE=prod
                volumes:
                  - "$LOG_SPRING_DIR:/app/logs"
                  - "$SEC_DIR:/app/config:ro"
                depends_on:
                  fastapi_backend:
                    condition: service_healthy
                restart: unless-stopped
                logging: { driver: json-file, options: { max-size: "10m", max-file: "5" } }
                extra_hosts: [ "host.docker.internal:host-gateway" ]
            YAML

            # 4) Deploy (always replace both)
            sudo docker compose -f "$STACK_DIR/compose.yml" pull
            sudo docker compose -f "$STACK_DIR/compose.yml" up -d --pull always --force-recreate

            # 5) Clean up old images
            sudo docker image prune -f
